apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        image: image-registry.openshift-image-registry.svc:5000/qa-alago/test:2022-02-15-18-31-05

